### ISSUE TITLE
Examples/Demos down?

### ISSUE THREAD

**Issue by bruno-f-cruz** [bonvision/BonVision#21]
Hi,

It seems the examples and demos on the BonVision website are down. Moreover, I cant seem to find them in the repo nor in Bonsai gallery either.
Any chance they can be reuploaded? 

Thanks,
Bruno

**Comment by amansaleem** [comment]
you can try this link. 
 https://github.com/bonvision/examples

looks like the links on the website are wrong and I'll fix that.

**Comment by bruno-f-cruz** [comment]
Great thanks!
