### ISSUE TITLE
DrawGratings does not display correct SF and orientation if ExtentX and ExtentY are different

### ISSUE THREAD

**Issue by znamensk** [bonvision/BonVision#7]
The issue arises largely due to the way grating angle is implemented in the vertex shader. The workflow passes a transformation matrix that applies a rotation to the texture coordinates `vt`. For example, as that matrix depends only on the orientation property, a 45 degree grating would always be oriented along the quad diagonal.

**Comment by amansaleem** [comment]
> The issue arises largely due to the way grating angle is implemented in the vertex shader. The workflow passes a transformation matrix that applies a rotation to the texture coordinates `vt`. For example, as that matrix depends only on the orientation property, a 45 degree grating would always be oriented along the quad diagonal.

Interesting, we never noticed it as we mostly use squares or circular masks. Will look into it.

**Comment by znamensk** [comment]
I've made a pull request with a proposed fix. Hopefully everything makes sense. Let me know otherwise.
